# Generated by Django 3.1.14 on 2024-02-01 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=129)),
                ('slug', models.SlugField(max_length=130)),
            ],
            options={
                'verbose_name': 'Exercises Type',
                'verbose_name_plural': 'Exercises Types',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('desired_weight', models.IntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2024, 2, 1, 19, 28, 12, 768824, tzinfo=utc))),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitnessAPI.sex')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pictures', models.FileField(upload_to='exercises/pictures')),
                ('calories_burnt_per_hr', models.IntegerField()),
                ('time', models.TimeField()),
                ('slug', models.SlugField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitnessAPI.exercisestype')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
    ]
